name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dev deps
        run: |
          npm install -D
      - name: Run linters
        run: |
          npm run lint
          npm run prettier:check

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: "--force"
          git_remote_url: ${{ secrets.DOKKU_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
