name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
      - name: Install dev deps
        run: |
          npm install -D
      - name: Run linters
        run: |
          npm run lint
          npm run prettier:check

  dokku:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: "--force"
          git_remote_url: ${{ secrets.DOKKU_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.rivit.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./prod.Dockerfile
          push: true
          tags: registry.rivit.dev/ptf:latest
